// <auto-generated />
using System;
using CdrBilling.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CdrBilling.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CdrBilling.Domain.Entities.BillingSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("error_message");

                    b.Property<int>("ProcessedRecords")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("processed_records");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<int>("TotalRecords")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("total_records");

                    b.HasKey("Id")
                        .HasName("pk_billing_sessions");

                    b.ToTable("billing_sessions", (string)null);
                });

            modelBuilder.Entity("CdrBilling.Domain.Entities.CallRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AccountCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("account_code");

                    b.Property<long?>("AppliedTariffId")
                        .HasColumnType("bigint")
                        .HasColumnName("applied_tariff_id");

                    b.Property<int>("BillableSec")
                        .HasColumnType("integer")
                        .HasColumnName("billable_sec");

                    b.Property<string>("CallId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("call_id");

                    b.Property<string>("CalledParty")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("called_party");

                    b.Property<string>("CallingParty")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("calling_party");

                    b.Property<decimal?>("ComputedCharge")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)")
                        .HasColumnName("computed_charge");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("direction");

                    b.Property<string>("Disposition")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("disposition");

                    b.Property<int>("DurationSec")
                        .HasColumnType("integer")
                        .HasColumnName("duration_sec");

                    b.Property<DateTimeOffset>("EndTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_time");

                    b.Property<decimal?>("OriginalCharge")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)")
                        .HasColumnName("original_charge");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<DateTimeOffset>("StartTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_time");

                    b.Property<string>("TrunkName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("trunk_name");

                    b.HasKey("Id")
                        .HasName("pk_call_records");

                    b.HasIndex("AppliedTariffId")
                        .HasDatabaseName("ix_call_records_applied_tariff_id");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("ix_cr_session");

                    b.HasIndex("SessionId", "CalledParty")
                        .HasDatabaseName("ix_cr_called");

                    b.HasIndex("SessionId", "CallingParty")
                        .HasDatabaseName("ix_cr_calling");

                    b.HasIndex("SessionId", "Disposition", "CalledParty")
                        .HasDatabaseName("ix_cr_session_disposition_called");

                    b.HasIndex("SessionId", "Disposition", "CallingParty")
                        .HasDatabaseName("ix_cr_session_disposition_calling");

                    b.ToTable("call_records", (string)null);
                });

            modelBuilder.Entity("CdrBilling.Domain.Entities.Subscriber", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("client_name");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("phone_number");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.HasKey("Id")
                        .HasName("pk_subscribers");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("ix_sub_session");

                    b.HasIndex("SessionId", "PhoneNumber")
                        .HasDatabaseName("ix_sub_phone");

                    b.ToTable("subscribers", (string)null);
                });

            modelBuilder.Entity("CdrBilling.Domain.Entities.TariffEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("ConnectionFee")
                        .HasPrecision(10, 6)
                        .HasColumnType("numeric(10,6)")
                        .HasColumnName("connection_fee");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("destination");

                    b.Property<DateOnly>("EffectiveDate")
                        .HasColumnType("date")
                        .HasColumnName("effective_date");

                    b.Property<DateOnly?>("ExpiryDate")
                        .HasColumnType("date")
                        .HasColumnName("expiry_date");

                    b.Property<string>("Prefix")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("prefix");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<decimal>("RatePerMin")
                        .HasPrecision(10, 6)
                        .HasColumnType("numeric(10,6)")
                        .HasColumnName("rate_per_min");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<TimeOnly>("TimebandEnd")
                        .HasColumnType("time without time zone")
                        .HasColumnName("timeband_end");

                    b.Property<TimeOnly>("TimebandStart")
                        .HasColumnType("time without time zone")
                        .HasColumnName("timeband_start");

                    b.Property<byte>("WeekdayMask")
                        .HasColumnType("smallint")
                        .HasColumnName("weekday_mask");

                    b.HasKey("Id")
                        .HasName("pk_tariff_entries");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("ix_te_session");

                    b.HasIndex("SessionId", "Prefix")
                        .HasDatabaseName("ix_te_prefix");

                    b.ToTable("tariff_entries", (string)null);
                });

            modelBuilder.Entity("CdrBilling.Domain.Entities.CallRecord", b =>
                {
                    b.HasOne("CdrBilling.Domain.Entities.TariffEntry", "AppliedTariff")
                        .WithMany()
                        .HasForeignKey("AppliedTariffId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_call_records_tariff_entries_applied_tariff_id");

                    b.Navigation("AppliedTariff");
                });
#pragma warning restore 612, 618
        }
    }
}
